### PR TITLE
Notes on Datatools Exercise

### PR DESCRIPTION
**Pull request by elenajal**
This pull request contains some notes on spelling corrections and additional instructions specific to MacOS users.

### CODE REVIEW

**Comment by VeenDuco** [comment]
This is great, thank you so much for contributing! I will merge your pull request!

**Review by VeenDuco — APPROVED** [review]
Textual suggestions that improve upon the current version and MacOS specific instructions.

**Comment by VeenDuco** [comment]
I don't seem to have "write access" to merge the pull request. @J535D165 @Rensvandeschoot, can you merge this PR and if possible grant me rights for the asreview-acadamy repo?

**Comment by J535D165** [comment]
Thanks!

**Pull request merged**
