### PR TITLE
Changed 'Exploration' to 'Validation'

### PR DESCRIPTION
**Pull request by Rensvandeschoot**
Work by @Metais , see https://github.com/asreview/asreview-academy/issues/24

### CODE REVIEW

**Comment by Rensvandeschoot** [comment]
Should we replace the PNG file with a direct link to https://github.com/asreview/asreview/tree/main/docs/images?

**Review by sjardi — APPROVED** [review]
All occurrences of "exploration" are changed to "validation" and are in line with the rest of the lab.

**Review by VeenDuco — APPROVED** [review]
Seems to be all okay. Even with screenshot update. Very nice.

**Comment by Rensvandeschoot** [comment]
Thanks all!

**Pull request merged**
